// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwjgcrnwyjmiivsemnql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3amdjcm53eWptaWl2c2VtbnFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzcwMDksImV4cCI6MjA3Mzk1MzAwOX0.KUNcoFsLocC94w7AIXtLIqDJ6EMINq46-BDn0EEd07w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});